server:
  port: 8082

spring:
  application:
    name: customer-service
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/vsms_customer_service}
    username: root
    password: ${MYSQL_ROOT_PASSWORD:root}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  flyway:
    enabled: true
    schemas: vsms_customer_service
    baselineOnMigrate: true
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: 5672

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}

management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus, metrics
